// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6MWV8NmPKQpOEK_WBrAwhb4oVCBnwfs',
    appId: '1:542512914910:web:42ae3cc43dc8e11654bd4f',
    messagingSenderId: '542512914910',
    projectId: 'tiktok-clone-ke',
    authDomain: 'tiktok-clone-ke.firebaseapp.com',
    storageBucket: 'tiktok-clone-ke.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6KMAwANniO8rs4kQ4rPXUEgvUNjD5O8',
    appId: '1:542512914910:android:0704c7af3199286c54bd4f',
    messagingSenderId: '542512914910',
    projectId: 'tiktok-clone-ke',
    storageBucket: 'tiktok-clone-ke.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxi6_iqIOL2Xbyw_O4colISIe7gQHuV9U',
    appId: '1:542512914910:ios:23f4b7194bd2e0e954bd4f',
    messagingSenderId: '542512914910',
    projectId: 'tiktok-clone-ke',
    storageBucket: 'tiktok-clone-ke.appspot.com',
    iosClientId: '542512914910-rmit4o502nnrhgce3a1prmogqo0l8vus.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );
}
